name: z_pay
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

  dots_indicator: ^2.1.0
  provider: ^6.0.3
  phonenumbers: ^1.1.0
  mask_text_input_formatter: ^2.3.0
  local_auth: ^2.1.0
  circular_countdown_timer: ^0.2.2



flutter:


  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/profile/
    - assets/images/faq/
    - assets/images/payments/
    - assets/images/profile/images/
    - assets/images/profile/profile_icons/
    - assets/images/instruction/
    - assets/images/login/
    - assets/images/myID/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/profile/HindSiliguri-Medium.ttf
          style: italic

